name: py爬蟲自動更新

on:
  schedule:
    - cron: '00 04 * * *'  # 对应台北时间00:00
  workflow_dispatch:
  push:
    branches:
      - master  # 仅在 master 分支触发工作流


permissions:
  contents: write  # 需要写权限，才能提交更改

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # 检出代码

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python script to generate JSON
      run: |
        python crawer.py  # 执行 Python 脚本，生成 JSON 文件

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        
        git add docs/assets/seven_eleven_products.json docs/assets/family_mart_stores.json
        git diff --cached --exit-code || git commit -m "Add generated JSON files to docs/assets"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的 token 来认证
